name: Suburban Boys
favicon: null
layout_spectrum: 0
typography_spectrum: 0.41554988687857985
title: Suburban Days
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#ad9573'
    - '#766049'
    - '#35241a'
  brandStrength: 0.4375
  lightness: 0.06509735644795
  saturation: 0.5841478263027966
  rhythmicContrast: 0.9528656536713243
purpose: []
